packages:
  - packages/**

allowBuilds:
  esbuild: true

catalogs:
  dev:
    "@arethetypeswrong/core": 0.18.5
    "@types/node": 26.4.0
    "@virtual-live-lab/tsconfig": 2.1.23
    pkg-pr-new: 0.0.88
    publint: 0.3.24
    typescript: 7.0.2
    unplugin-unused: 0.6.0
    vite-plus: 0.3.0

saveExact: true
