packages:
  - packages/**

allowBuilds:
  esbuild: true

catalogs:
  dev:
    "@arethetypeswrong/core": 0.18.5
    "@types/node": 26.1.1
    "@typescript/native-preview": 7.0.0-dev.20260618.1
    "@virtual-live-lab/tsconfig": 2.1.23
    pkg-pr-new: 0.0.79
    publint: 0.3.22
    typescript: 6.0.3
    unplugin-unused: 0.5.7
    vite-plus: 0.2.5

saveExact: true
